config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'users/:id', to: 'users#show', as: :user_profile
  resources :notifications, only: :index
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :feedbacks, only: [:create, :edit, :update, :show] do
      resources :votes, only: [:create, :destroy]
    end
  end

  resources :categories, only: [:show]

  authenticate :user, ->(user) { user.admin? } do
  mount Blazer::Engine, at: "blazer"
  end
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-color: white">
  <div class="banner-container">
    <h1><strong>Breakfast of Champions</strong>
      <br>
     <strong> The peer to peer feedback platform for creatives.</strong></h1>
    <br>
     <div data-aos="fade-down-right" data-aos-duration="2000"
    data-aos-easing="ease-in-out"> <%= image_tag "boc_new_21", size: "491x426", class: "image-banner"%></div>

    <p>Get constructive <strong>feedback</strong> from the community.
      <br>Take your work to the <strong>next level</strong>.</p>
    <br>
    <br>
    <br>
    <br>
        <%= link_to "Create a Profile", new_user_registration_path, class: "btn btn-flat bubbly-button" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-wrapper">
  <div class="footer">
    <div class="footer-logo-container">
        <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "boc_10", class: "footer-logo" %>
        <% end %>
      <h6>Breakfast of Champions</h6>
    </div>
    <div class="responsive-links">
      <div class="footer-navigate-container">
        <h6> <%=link_to "Explore", posts_path, class: "navigate-text" %> </h6>
        <h6> <%=link_to "Sign up", new_user_registration_path, class: "navigate-text" %> </h6>
      </div>
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
    <h6 class="copyright-text">Breakfast of Champions &copy 2020</h6>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="nvbr">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "boc_10.png" %>
  <% end %>
  <div class="d-flex flex-row navbar-search" style="justify-content: center; flex-grow: 1;">
    <!-- search bar -->
    <form novalidate="novalidate" class="search" action="/posts" accept-charset="UTF-8" method="get">
      <input name="utf8" type="hidden" value="&#x2713;" />
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="query" id="search_query" value="<%= params[:query] %>" />
        <button name="button" type="submit" class="btn btn-flat">
          <p>Search for... <i class="fas fa-search"></i></p>
        </button>
      </div>
    </form>
  </div>

  <!-- links on navbar -->
  <div class="collapse navbar-collapse nav-item navbar-active" type="button" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item" class="nav-link">
        <%= link_to "Get Feedback", new_post_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Explore", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <div id="flag-container" data-chatroom-id="<%= current_user.id %>">
          <%= link_to notifications_path, class: "nav-link" do %>
            <i id="nav-flag" class="far fa-flag fa-sm"></i>
          <% end %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Explore", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>

  <!-- avatar with dropdown menu -->
  <div class="nav-item dropdown nav-avatar">

    <% if user_signed_in? %>
      <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
       <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to "Dashboard", user_profile_path(current_user.username), class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
      <% else %>
      <div class="avatar-initials-navbar" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.username[0..1].upcase %>
      </div>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to "Dashboard", user_profile_path(current_user.username), class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
      <% end %>
    <% end %>
  </div>

   <!-- toggle button on small device -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>