config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'users/:id', to: 'users#show', as: :user_profile
  resources :notifications, only: :index
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :feedbacks, only: [:create, :edit, :update, :show] do
      resources :votes, only: [:create, :destroy]
    end
  end

  resources :categories, only: [:show]

  authenticate :user, ->(user) { user.admin? } do
  mount Blazer::Engine, at: "blazer"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  before_destroy :destroy_notifications
  belongs_to :user
  has_many :feedbacks, dependent: :destroy
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories

  #has_many :notifications, through: :feedbacks, dependent: :destroy


  has_many_attached :photos

  validate :has_attached_image

  validates :title, presence: true
  validates :description, presence: true

  def has_attached_image
    unless self.photos.attached?
      errors.add(:number_of_photos, "Needs at least one photo")
    end
  end

  def notifications
    # Exact match
    # @notifications ||= Notification.where(params: { post: self })

    # Or Postgres syntax to query the post key in the JSON column
    @notifications ||= Notification.where("params->'post' = ?", Noticed::Coder.dump(self).to_json)
  end


  def destroy_notifications
    notifications.destroy_all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [ :index ]

  def index
    if params[:query].present?
      sql_query = " \
        posts.title ILIKE :query \
        OR posts.description ILIKE :query \
        OR categories.name ILIKE :query \
      "
      @pagy, @posts = pagy(Post.joins(:categories).where(sql_query, query: "%#{params[:query]}%"), items: 15)
    else
      @pagy, @posts = pagy(Post.all.order(created_at: :desc), items: 15)
    end
    @categories = Category.all
  end

  def show
    @feedback = Feedback.new
    if params[:notification_id].present?
      @notification = Notification.find(params[:notification_id])
      @notification.mark_as_read!
    end
    @post.views = @post.views + 1
    @post.save
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post, notice: 'A post was successfully created.'

    else
      p @post.errors.full_messages
      render :new, alert: 'Something went wrong.'
    end
    UserChannel.broadcast_to(
      @post.user, "test"
    )
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def my_posts
    @posts = current_user.posts
  end

  def destroy
    @post.destroy
    redirect_to user_profile_path(current_user.username), notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, photos: [], category_ids: [])
  end
end

app/views/posts/_form.html.erb
<div class="collapse" id="collapseExample<%= feedback_id %>">
  <%= simple_form_for([@post, @feedback], remote: true) do |f| %>
    <%= f.input :feedback_id, input_html: {value: feedback_id}, as: :hidden %>
    <%= f.input :description, label: false %>
    <%= f.button :submit, "Reply", class: 'btn btn-info' %>
  <% end %>
</div>

<a class= "post-reply inline-button" data-toggle="collapse" href="#collapseExample<%= feedback_id %>" role="button" aria-expanded="false" aria-controls="collapseExample<%= feedback_id %>">
<!-- <i class="far fa-comment-dots"></i> -->
reply
</a>

app/views/posts/_post.html.erb
  <div class="general-container <%= 'nested' if level != 0 %>">
    <div class="feedback-container <%= level == 0 ? 'top' : 'not-top' %>" id="feedback-post" style="padding-left: <%= level * 30 %>px">
      <div class="feedbacks-container">
        <div class="reply-space">



          <div class="left">
            <div class="reply-1" >
              <strong>
                <%= Vote.where(feedback: feedback).count%>
              </strong>
            </div>
            <% vote = Vote.where(feedback: feedback, user: current_user).first %>
            &#160;

            <% if vote %>
            <%= button_to post_feedback_vote_path(feedback.post, feedback, vote), method: :delete, remote: true do %>
            <i class="fas fa-caret-square-down"></i>
            <% end %>
            <% else %>
            <%= button_to post_feedback_votes_path(feedback.post, feedback), remote: true do %>
            <i class="fas fa-caret-square-up"></i>
            <% end %>
            <% end %>

            <div class="user-link">
              -<%= link_to feedback.user.username, user_profile_path(feedback.user.username), class: "a-reply user-link",
              style: "font-size: 15px";
              %>
            </div>

          </div>


          <div class="actions">
            <% if current_user.id == feedback.user_id %>
            <button type="button" class="inline-button" data-toggle="collapse" data-target="#collapse<%=feedback.id%>" aria-expanded="false" aria-controls="collapseExample">
              edit
            </button>
            <!-- <i class="fas fa-pencil-alt edit-post-1" type="button" data-toggle="collapse" data-target="#collapse<%=feedback.id%>" aria-expanded="false" aria-controls="collapseExample"></i> -->
            <% end %>

          </div>
        </div>
      </div>
      <div class="feedback-description-container">
        <p>
          <%= feedback.description %>
        </p>
      </div>
       <%= render partial: "posts/form", locals: { feedback_id: feedback.id }%>
    </div>

    <div class="collapse" id="collapse<%=feedback.id%>">
      <div class="card card-body">
        <p>Edit your feedback</p>
        <%= simple_form_for([@post, feedback], remote: true) do |f| %>
        <%= f.input :description, label: false %>
        <%= f.button :submit, class: 'btn btn-info-reply' %>
        <% end %>
      </div>
    </div>




    <% feedback.feedbacks.each do |feedback| %>
    <%= render partial: "posts/post", locals: { feedback: feedback, level: (level += 1) } %>
    <% end %>
  </div>

  <!--  -->

app/views/posts/edit.html.erb
<div id="editpostpage" class="container p-5">
  <div class="row justify-content-center">
    <div id="column" class="col-12">
      <div class="col-md-12">
       <h1>Edit post</h1>
        <%= simple_form_for @post do |f| %>
        <%= f.input :title, input_html: { maxlength: 50 }%>
        <%= f.input :description, input_html: { maxlength: 500 } %>
        <%= f.input :photos, as: :file, input_html: {class: 'd-none hidden', multiple: true, accept: ".pdf", id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '✉︎ Upload a PDF file (1 page only)' %>
        <embed src="" id="photo-preview" type="" class="hidden-embed-pdf">
        <%= f.input :category_ids, collection: Category.all, as: :check_boxes, label_method: :name, input_html: { class: "tag-selector" }, item_wrapper_class: 'tag-item' %>
        <div class="center">
          <%= f.button :submit, class: 'btn-edit-responsive' %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="categories-container">
  <h2>Browse by category:</h2>
<% @categories.each do |category| %>
 <button class="btn-info-categories" style="opacity: 0.8;"><%= link_to category.name, category_path(category.slug) %>
</button>
<% end %>
</div>

<br>
<div class="index-container">
<div class="cards">
  <% @posts.each do |post| %>
  <div class="card">
    <%= link_to '', post_path(post), class:"no-hover-link card-link" %>
    <div class="card-inner-content">
      <div class="card-outer d-flex justify-content-center" >
        <% if post.photos.attached? %>
        <div id="carouselExampleControls" data-interval="3500" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
        <% post.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= 'active' if index.zero? %>">
          <%=cl_image_tag "#{photo.key}.jpg", class: "card-picture d-block w-100 "%>
            </div>
        <% end %>
          </div>
        </div>
        <% else %>
          <div class="card-picture" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= cl_image_path post.photos.first.key %>)">
        <% end %>
      </div>
      <div class="card-infos">
        <div class="row">
          <div class="col-10">
            <br>
            <h6><strong> <%= post.title %> </strong></h6>
            <%= link_to user_profile_path(post.user.username), class:"a-reply" do %>
              <h6><%= post.user.username.capitalize %></h6>
            <% end %>
            <% post.categories.each do |category| %>
              <button class="btn-info-post" style="opacity: 0.8;">
                <%= link_to category.name, category_path(category.slug) %>
              </button>
            <% end %>
          </div>
          <div class="col-2">
            <br>
            <div class="icon"><i class="fas fa-comment fa-sm"></i></i> <i class="fas fa-eye fa-sm"></i></div>
            <div class="icon-text"><p><%= post.feedbacks.count %> </p><p> <%= post.views %> </p></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="container-index">
<div class="row">
  <div class="col-8">
  <%== pagy_bootstrap_nav(@pagy).html_safe%>
    </div>
  </div>
  </div>
  </div>

</div>

app/views/posts/new.html.erb
<div class="background">
<div class="container pt-5">
  <div class="row justify-content-center">
    <div id="column" class="col-12">
      <div class="col-md-12 form-container">
       <h2>How To Create a New Post in 4 Easy Steps:</h2>
       <br>
       <ul>
         <li> <h5> <i class="fas fa-arrow-circle-up"></i>  -  1. Upload your work  </h5></li>
         <li> <h5> <i class="fas fa-question-circle"></i>  -  2. Ask your question to the community  </h5></li>
         <li> <h5> <i class="fas fa-comments"></i>  -  3. Get feedback  </h5></li>
         <li> <h5> <i class="fas fa-sort-amount-up"></i>  -  4. Take your work to the next level ! </h5></li>
       </ul>

       <br>
       <br>

        <div class="form-box">
       <h3 class="black-text">Create a Post</h3>
       <br>
       <%= simple_form_for @post do |f| %>
       <%= f.input :title, input_html: { maxlength: 50 }%>
       <%= f.input :description, input_html: { maxlength: 500 } %>
       <%= f.input :photos, as: :file, input_html: {class: 'd-none hidden', multiple: true, accept: ".pdf", id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '↑ Upload a PDF' %>
       <embed src="" id="photo-preview" type="" class="hidden-embed-pdf">
        <%= f.input :category_ids, collection: Category.all, as: :check_boxes, label_method: :name, input_html: { class: "tag-selector" }, item_wrapper_class: 'tag-item' %>
        <div class="center">
        <%= f.button :submit, value: 'Publish Post!', data: {disable_with: "publishing post..."}, class: 'btn btn-info-reply' %></div>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/posts/show.html.erb
<% content_for :meta_title, "#{@post.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @post.description %>
<% photo = @post.photos.attached? ? @post.photos.first.key : "obt2gawnkhhze7popquskpu4gxop" %>
<% content_for :meta_image, cl_image_path(photo) %>

<div class="row px-5">
  <div class="col-8 py-5">
    <div class="post d-flex justify-content-center">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% @post.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= 'active' if index.zero? %>">
                <%= cl_image_tag "#{photo.key}.jpg", class: "d-block w-100 card-detail", crop: :fill, height: 500, id: "post-img"%>
              </div>
          <% end %>

        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <% if @post.user == current_user %>
    <%= link_to edit_post_path do %>
    <i class="fas fa-edit" id="edit-post"></i>
    <% end %>
    <%= link_to post_path(@post), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fas fa-trash-alt" id="delete"></i>
    <% end %>
    <% end %>
  </div>

  <div class="col-4" id="post-description">
    <div class="post-description">
      <h4><%= @post.title %></h4>
      <h5><%= @post.description %></h5>
        <p>Work by: <%= link_to @post.user.username.capitalize,  user_profile_path(@post.user.username), class: "a-reply" %></p>
          <p style="font-size: 13px; margin-top: -16px;"> Posted: <%= @post.created_at.strftime("%m/%d/%y") %></p>

      <% @post.categories.each do |category| %>
      <button class="btn-info-1" style="opacity: 0.8; margin: 10px 0; margin-top: 0px;">
      <%= category.name %>
      </button>
      <% end %>


      <div class="post-feedback">
        <%= simple_form_for([@post, @feedback], remote: true) do |f| %>
        <%= f.input :description, label: false %>
        <div class="btn-container">
        <button class="btn btn-info-reply" style="margin-bottom: 35px;"><%= f.button :submit, 'Share Feedback'%></button>
        </div>
        <% end %>
        <% @post.feedbacks.where(feedback_id: nil).reverse.each do |feedback| %>
        <%= render partial: "posts/post", locals: { feedback: feedback, level: 0 } %>
        <% end %>

    </div>
  </div>
      </div>
</div>